---
title: "sentimentor_analyses"
author: "Alexander Fiksdal"
date: "2/6/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(car)
library(Metrics)
library(MLmetrics)
library(betareg)
library(knitr)
```

```{r read_data}
df = read.csv('data/processed/would_recommend.csv')
colnames(df)
raw_values = colnames(df)[1:13]
top_values = colnames(df)[c(1, 3, 5, 7, 9, 11, 13)]
ratio_values = c("would_recommend", colnames(df)[14:19])
adj_values = c("would_recommend", colnames(df)[20:25])
managed_values = c("would_recommend", colnames(df)[26:31])
```

```{r would_recommend_raw}
m_raw = lm(would_recommend ~ .-EMO_REL_BBV, data=df[raw_values])
summary(m_raw)
rmse(df$would_recommend, predict(m_raw, df[raw_values]))
mae(df$would_recommend, predict(m_raw, df[raw_values]))
```

```{r would_recommend_top}
m_top = lm(would_recommend ~ ., data=df[top_values])
summary(m_top)
rmse(df$would_recommend, predict(m_top, df[top_values]))
mae(df$would_recommend, predict(m_top, df[top_values]))
vif(m_top)
```

```{r would_recommend_adj}
m_adj = lm(would_recommend ~ ., data=df[ratio_values])
summary(m_adj)
rmse(df$would_recommend, predict(m_adj, df[ratio_values]))
mae(df$would_recommend, predict(m_adj, df[ratio_values]))

```

```{r would_recommend_man}
m_man = lm(would_recommend ~ ., data=df[managed_values])
summary(m_man)
rmse(df$would_recommend, predict(m_man, df[managed_values]))
mae(df$would_recommend, predict(m_man, df[managed_values]))
vif(m_man)
```

```{r would_recommend_mid}
df_mid = read.csv('data/processed/middle_vars.csv')
m_mid = lm(would_recommend ~ ., data=df_mid)
summary(m_mid)
rmse(df_mid$would_recommend, predict(m_mid, df_mid))
mae(df_mid$would_recommend, predict(m_mid, df_mid))
vif(m_mid)
```
