#%% Raw file paths
cahps_path = 'data/raw/cms/Hospice_Compare_-_Provider_CAHPS_Hospice_Survey_Data.csv'
provider_path = 'data/raw/cms/Hospice_-_Provider_Data.csv'
simple_maps_path = 'data/raw/cms/uscities.csv'
county_ll_path = 'data/raw/cms/counties.csv'
facility_data_path = 'data/raw/cms/Hospice_-_General_Information.csv'
puf_path = 'data/raw/cms/PAC Provider PUF_v20191002.csv'

#%% Variable lists
service_vars_mid = [
    'EMO_REL_TBV',
    'RESPECT_MBV',
    'SYMPTOMS_MBV',
    'TEAM_COMM_MBV',
    'TIMELY_CARE_MBV',
    'TRAINING_MBV']

service_bottom_top = [
    'EMO_REL_BBV',
    'EMO_REL_TBV',
    'RESPECT_BBV',
    'RESPECT_TBV',
    'SYMPTOMS_BBV',
    'SYMPTOMS_TBV',
    'TEAM_COMM_BBV',
    'TEAM_COMM_TBV',
    'TIMELY_CARE_BBV',
    'TIMELY_CARE_TBV',
    'TRAINING_BBV',
    'TRAINING_TBV']

ratio_vars = ['EMO_REL_BTR',
    'RESPECT_BTR',
    'SYMPTOMS_BTR',
    'TEAM_COMM_BTR',
    'TIMELY_CARE_BTR',
    'TRAINING_BTR']

adj_vars = ['EMO_REL_ADJ',
    'RESPECT_ADJ',
    'SYMPTOMS_ADJ',
    'TEAM_COMM_ADJ',
    'TIMELY_CARE_ADJ',
    'TRAINING_ADJ']

managed_vars = [
    'MANAGED_EMO_REL',
    'MANAGED_RESPECT',
    'MANAGED_SYMPTOMS',
    'MANAGED_TEAM_COMM',
    'MANAGED_TIMELY_CARE',
    'MANAGED_TRAINING']

dense_vars = [
    'for_profit',
    'n_win_60',
    'H_009_01_OBSERVED',
    'MANAGED_EMO_REL',
    'MANAGED_SYMPTOMS',
    'MANAGED_TEAM_COMM',
    'MANAGED_TIMELY_CARE',
    'MANAGED_TRAINING',
    'percBen30orFewerDays',
    'nurseVisitCtPB',
    'socialWorkCtPB',
    'physicianCtPB',
    'percRuralZipBen'
]

sparse_vars = [
 'Ownership Type_For-Profit',
 'Ownership Type_Government',
 'Ownership Type_Non-Profit',
 'Ownership Type_Other',
 'Care_Provided_Assisted_Living_Yes',
 'Care_Provided_Home_Yes',
 'Care_Provided_Inpatient_Hospice_Yes',
 'Care_Provided_Inpatient_Hospital_Yes',
 'Care_Provided_Nursing_Facility_Yes',
 'Care_Provided_Skilled_Nursing_Yes',
 'Care_Provided_other_locations_Yes',
 'Provided_Home_Care_and_other_Yes',
 'Ownership Type_Combination Government & Non-Profit',
 'Provided_Home_Care_only_Yes',
 'days_operation',
 'n_win_30',
 'n_win_60',
 'n_win_90',
 'nearest',
 'epStayCt',
 'percRuralZipBen',
 'totChargePB',
 'totalMedStandPayPB',
 'tot_med_PB',
 'distinctBens',
 'daysService',
 'percDaysHospRHC',
 'aveHCCscore',
 'aveAge',
 'percSOSDhome',
 'nurseVisitCtPB',
 'homeHealthCtPB',
 'socialWorkCtPB',
 'percSOSDassisLiv',
 'aveHomeHealth7dp',
 'aveSocialWork7dp',
 'aveNurseMin7dp',
 'percSOSlongtermcare',
 'percSOSinpatientHospice',
 'percSOSskilledNurse',
 'percWhite',
 'percSOSinpatient',
 'H_001_01_OBSERVED',
 'H_002_01_OBSERVED',
 'H_003_01_OBSERVED',
 'H_005_01_OBSERVED',
 'physicianCtPB',
 'H_008_01_OBSERVED'
]

#%% Variable Dicts
feature_groups = {
    'Service Quality': ['EMO_REL_BTR', 'RESPECT_BTR', 'SYMPTOMS_BTR',
                        'TEAM_COMM_BTR', 'TIMELY_CARE_BTR', 'TRAINING_BTR'],
    'Services Delivered': ['H_009_01_OBSERVED', 'percSOSDassisLiv',
                           'nurseVisitCtPB', 'socialWorkCtPB',
                           'physicianCtPB'],
    'Services Offered': ['Care_Provided_Assisted_Living_Yes',
                         'Care_Provided_Home_Yes',
                         'Care_Provided_Inpatient_Hospice_Yes',
                         'Care_Provided_Skilled_Nursing_Yes'],
    'Patients Served': ['percBlack', 'percHisp', 'percBen30orFewerDays'],
    'Financial Details': 'totalMedStandPayPB'
}


cahps_dict = {
    "TEAM_COMM_TBV": "The hospice team always communicated well",
    "TIMELY_CARE_BBV": "The hospice team sometimes or never provided timely help",
    "SYMPTOMS_BBV": "The patient sometimes or never got the help they needed for pain and symptoms",
    "RATING_BBV": "Caregivers rated the hospice agency a 6 or lower",
    "TEAM_COMM_MBV": "The hospice team usually  communicated well",
    "RESPECT_TBV": "The hospice team always treated the patient with respect",
    "RECOMMEND_TBV": "YES, they would definitely recommend the hospice",
    "EMO_REL_TBV": "The hospice team provided the right amount of emotional and spiritual support",
    "SYMPTOMS_MBV": "The patient usually got the help they needed for pain and symptoms",
    "TEAM_COMM_BBV": "The hospice team sometimes or never communicated well",
    "TRAINING_BBV": "They did not receive the training they needed",
    "RECOMMEND_MBV": "YES, they would probably recommend the hospice",
    "SYMPTOMS_TBV": "The patient always got the help they needed for pain and symptoms",
    "RESPECT_MBV": "The hospice team usually treated the patient with respect",
    "TIMELY_CARE_TBV": "The hospice team always provided timely help",
    "RATING_TBV": "Caregivers rated the hospice agency a 9 or 10",
    "TRAINING_MBV": "They somewhat received the training they needed",
    "EMO_REL_BBV": "The hospice team did |not| provide the right amount of emotional and spiritual support",
    "RECOMMEND_BBV": "NO, they would probably not or definitely not recommend the hospice",
    "RESPECT_BBV": "The hospice team sometimes or never treated the patient with respect",
    "RATING_MBV": "Caregivers rated the hospice agency a 7 or 8",
    "TIMELY_CARE_MBV": "The hospice team usually provided timely help",
    "TRAINING_TBV": "They definitely received the training they needed"
}

provider_dict = {
    "H_001_01_OBSERVED": "Hospice and Palliative Care Treatment Preferences",
    "H_002_01_OBSERVED": "Beliefs & Values Addressed (if desired by the patient)",
    "H_003_01_OBSERVED": "Hospice and Palliative Care Pain Screening",
    "H_004_01_OBSERVED": "Hospice and Palliative Care Pain Assessment",
    "H_005_01_OBSERVED": "Hospice and Palliative Care Dyspnea Screening",
    "H_006_01_OBSERVED": "Hospice and Palliative Care Dyspnea Treatment",
    "H_007_01_OBSERVED": "Patient Treated with an Opioid Who Are Given a Bowel Regimen",
    "H_008_01_OBSERVED": "Hospice and Palliative Care Composite Process Measure",
    "H_009_01_OBSERVED": "Hospice Visits When Death Is Imminent, Measure 1"
}

puf_dict = {
"distinctBens": "Distinct Beneficiaries",
"epStayCt": "Episode or Stay Count",
"daysService": "Days of Service",
"percBen7orFewerDays": "Percent of Beneficiaries with 7 or fewer Service Days",
"percBen30orFewerDays": "Percent of Beneficiaries with 30 or fewer Service Days",
"percBen60orFewerDays": "Percent of Beneficiaries with 60 or more Service Days",
"percBen180orFewerDays": "Percent of Beneficiaries with 180 or more Service Days",
"totalCharge": " Total Charge Amount ",
"totalMedStandPay": " Total Medicare Standard Payment Amount ",
"totalMedPay": " Total Medicare Payment Amount ",
"totalOutlierPay": "Total Outlier Payment Amount",
"totalAllowedAmt": "Total Allowed Amount",
"totalCoinsuranceAmt": "Total Coinsurance Amount",
"percMedAdvBen": "Percent Medicare Advantage Beneficiaries",
"percDualBen": "Percent Dual Beneficiaries",
"percRuralZipBen": "Percent Medicare Beneficiaries in a Rural ZIP",
"aveAge": "Average Age",
"percMale": "Percent Male Beneficiaries",
"percFemale": "Percent Female Beneficiaries",
"percWhite": "Percent White Beneficiaries",
"percBlack": "Percent Black Beneficiaries",
"percAsian": "Percent Asian Pacific Islander Beneficiaries",
"percHisp": "Percent Hispanic Beneficiaries",
"percNative": "Percent American Indian or Alaska Native Beneficiaries",
"percOther": "Percent Other/Unknown Beneficiaries",
"aveHCCscore": "Average HCC Score",
"aveNumChronicCond": "Average Number of Chronic Conditions",
"percBenAFib": "Percent of Beneficiaries with Atrial Fibrillation",
"percBenAlzheimers": "Percent of Beneficiaries with Alzheimer's",
"percBenAsthma": "Percent of Beneficiaries with Asthma",
"percBenCancer": "Percent of Beneficiaries with Cancer",
"percBenCHF": "Percent of Beneficiaries with CHF",
"percBenChronicKidney": "Percent of Beneficiaries with Chronic Kidney Disease",
"percBenCOPD": "Percent of Beneficiaries with COPD",
"percBenDepres": "Percent of Beneficiaries with Depression",
"percBenDiabetes": "Percent of Beneficiaries with Diabetes",
"percBenHyperlip": "Percent of Beneficiaries with Hyperlipidemia",
"percBenHypertens": "Percent of Beneficiaries with Hypertension",
"percBenIHD": "Percent of Beneficiaries with IHD",
"percBenOsteo": "Percent of Beneficiaries with Osteoporosis",
"percBenRAOA": "Percent of Beneficiaries with RA/OA",
"percBenSchiz": "Percent of Beneficiaries with Schizophrenia",
"percBenStroke": "Percent of Beneficiaries with Stroke",
"percBenCancer_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Cancer",
"percBenCOPD_Prim": "Percent of Beneficiaries with a Primary Diagnosis of COPD",
"percBenRespFail_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Respiratory Failure",
"percBenDementia_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Dementia",
"PercBenStroke_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Stroke",
"PercBenCHF_Prim": "Percent of Beneficiaries with a Primary Diagnosis of CHF",
"percBenHypertens_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Hypertension",
"percBenOtherCirc_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Other Circulatory/Heart Conditions",
"percBenInfect_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Infection",
"percBenMuscSkel_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Musculoskeletal and Connective Tissue Disorders",
"percBenInjury_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Injury",
"percBenMotorNeural_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Motor Neural Disease",
"percBenDiabetes_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Diabetes",
"percBenBurn_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Skin Ulcer/Burns",
"percBenAfterCare_Prim": "Percent of Beneficiaries with a Primary Diagnosis of Aftercare",
"nurseVisitCt": "Nursing Visit Count",
"ptCt": "Physical Therapy Visit Count",
"occupTherCt": "Occupational Therapy Visit Count",
"speechLangPathCt": "Speech Language Pathology Visit Count",
"socialWorkCt": "Social Work Visit Count",
"homeHealthCt": "Home Health Aide Visit Count",
"physicianCt": "Physician Visit Count",
"totalNurseMin": "Total Nursing Minutes",
"totalPTMin": "Total Physical Therapy Minutes",
"totalOccuTherMin": "Total Occupational Therapy Minutes",
"totalSpeechLangMin": "Total Speech-Language Pathology Minutes",
"totalSocialWorkMin": "Total Social Work Minutes",
"totalHomeHealthMin": "Total Home Health Aide Minutes",
"aveNurseMin7dp": "Average Nursing Minutes, 7 Days Prior to Death",
"aveSocialWork7dp": "Average Social Work Minutes, 7 Days Prior to Death",
"aveHomeHealth7dp": "Average Home Health Aide Minutes, 7 Days Prior to Death",
"assessDenom": "Assessment Denominator",
"percRV10minthresh": "Percentage of RV Assessments within 10 minutes of Threshold",
"percRU10minthresh": "Percentage of RU Assessments within 10 minutes of Threshold",
"percSOSDhome": "Percentage Site of Service Days, Home",
"percSOSDassisLiv": "Percentage Site of Service Days, Assisted Living Facility",
"percSOSlongtermcare": "Percentage Site of Service Days, Long-Term Care Facility",
"percSOSskilledNurse": "Percentage Site of Service Days, Skilled Nursing Facility",
"percSOSinpatient": "Percentage Site of Service Days, Inpatient Hospital",
"percSOSinpatientHospice": "Percentage Site of Service Days, Inpatient Hospice",
"percComSelfDisch": "Percentage with a Community/Self-Care Discharge Status",
"percInpatientHospDisch": "Percentage with an Inpatient Hospital Discharge Status",
"percHomeHealthDisch": "Percentage with a Home Health Discharge Status",
"percSkilledNurseDisch": "Percentage with a Skilled Nursing Facility Discharge Status",
"percInpatientRehapDisch": "Percentage with an Inpatient Rehabilitation Facility Discharge Status",
"percHospDisch": "Percentage with a Hospice Discharge Status",
"percDeathDisch": "Percentage with a Death Discharge Status",
"percUnkDisch": "Percentage with an Unknown Discharge Status",
"percHospLiveDisch": "Percentage of Hospice Live Discharges",
"percDaysHospRHC": "Percent of Days in Hospice RHC"
}